class GameSettings {
  constructor({ BLOCK_SIZE, FRAME_WIDTH, FRAME_HEIGHT }) {
    this.BLOCK_SIZE = BLOCK_SIZE
    this.FRAME_WIDTH = FRAME_WIDTH
    this.FRAME_HEIGHT = FRAME_HEIGHT
    this.WIDTH_IN_BLOCKS = FRAME_WIDTH / BLOCK_SIZE
    this.HEIGHT_IN_BLOCKS = FRAME_HEIGHT / BLOCK_SIZE
  }
}

export default new GameSettings({
  BLOCK_SIZE: 20,
  FRAME_WIDTH: 400,
  FRAME_HEIGHT: 600,
})
